### ISSUE TITLE
Siddhantakaumudi etc. missing?

### ISSUE THREAD

**Issue by kmadathil** [indic-dict/stardict-sanskrit-vyAkaraNa#15]
In a recent installation, I noticed that Siddhanta Kaumudi, Balamanorama, etc. are missing from the sanskrit-vyAkaraNa dictionaries list. Have they been removed or moved?

**Comment by vvasuki** [comment]
Removed. ashtadhyayi.com तन्त्रांशं स्थापयित्वा सरलतया ऽन्वेष्टुं शक्यम् इति।
