### ISSUE TITLE
SKD - add prAtipadika headwords

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit-vyAkaraNa#5]
As far as shabdakalpadruma is concerned - Right now you can search for rAmaH, not rAma. matiH, not mati. Was all right in the earlier version. Must be fixed to include these additional headwords - getting it is simple in most cases (see [make_simple_dict.py](https://github.com/sanskrit-coders/stardict-sanskrit/blob/23a3cac01899218d8f866e8a0d5b81af4a35e673/sa-head/sa-entries/kalpadruma-sa/mUlam/make_simple_dict.py) for what I'd done..).. kalpadruma is an important dict, people will miss being informed by it and this should be considered relatively high priority.

**Comment by drdhaval2785** [comment]
![screenshot_20190210-083234_colordict](https://user-images.githubusercontent.com/5755132/52528862-88d58f00-2d0e-11e9-9d12-3b87e37ff7e5.jpg)

**Comment by drdhaval2785** [comment]
Applied this feature for all dictionaries.
